{% set name = "insightface" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/insightface-{{ version }}.tar.gz
  sha256: f191f719612ebb37018f41936814500544cd0f86e6fcd676c023f354c668ddf7

build:
  entry_points:
    - insightface-cli=insightface.commands.insightface_cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 4
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pypandoc
    - pip
  run:
    - python
    - onnx
    - onnxruntime
    - opencv
    - tqdm
    - requests
    - matplotlib-base
    - pillow
    - scipy
    - scikit-learn
    - scikit-image
    - easydict
    - cython
    - albumentations
    - prettytable

test:
  imports:
    - insightface

about:
  home: https://github.com/deepinsight/insightface
  summary: InsightFace Python Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
